# Generated by Django 2.1.1 on 2018-09-22 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='henre',
            new_name='genre',
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_logo',
        ),
    ]
